### ISSUE TITLE
Recreate crontab after restart container

### ISSUE THREAD

**Issue by StefanRother-OTOBO** [RotherOSS/otobo-docker#14] opened 2020-09-09 09:32 UTC
Hi,

We add a new cronfile to /opt/otobovar/cron/ and execute bin/Cron.sh. After restart the otobo container the crontab entry is missing again. Perhaps we need to execute bin/Cron.sh again?

Thanks,

Stefan

**Comment by bschmalhofer** [comment] 2020-09-09 10:30
As of now, cronjobs should run on the Docker host. 

The cronjob support in the container otobo_cron_1 was only a workaround for providing an easy way for checking whether the Daemon is alive. This workaround is removed in OTOBO 10.0.x and that container was renamed to otobo_daemon_1. That the crontab in otobo_cron_1 does not survive a container restart is expected behavior.

If cronjobs in Docker are really a requirement, then I can add a dedicated container for that in OTOBO 10.0.3. My hunch is that the crontab flle could be put into the volume otobo_opt_otobo, This would avoid the need for yet another volume,
But let's discuss this first before proceeding.

**Comment by bschmalhofer** [comment] 2020-09-09 10:38
After looking at bin/Cron.sh it looks like this is meant as a general mechanism where packages can add cronjobs. So the decision is between removing that feature and  providing a container that runs cron. Preferably a version of cron that does not need root privs.

**Comment by bschmalhofer** [comment] 2020-09-18 08:23
This was discussed during the OTOBO Team Meeting. For now no support for cronjobs is needed. Closing the issue.

**Closed as completed by bschmalhofer** 2020-09-18 08:23 UTC
Labels: enhancement, wontfix
