### ISSUE TITLE
wrong standard config for install rel-11_0

### ISSUE THREAD

**Issue by nudfmf** [RotherOSS/otobo-docker#131] opened 2024-05-15 06:42 UTC
The standard config of Rel. 11_0 in the /docker-compose directory is still the same as rel_10_1
e.g. in the otobo-base.yml

According to the manual, version 10_1 is installed under the rel_11_0 tag

**Comment by bschmalhofer** [comment] 2024-05-15 07:36
I can confirm that:
```
 grep image docker-compose/otobo-*.yml | grep rother
docker-compose/otobo-base.yml:    image: ${OTOBO_IMAGE_OTOBO:-rotheross/otobo:latest-10_1}
docker-compose/otobo-base.yml:    image: ${OTOBO_IMAGE_OTOBO:-rotheross/otobo:latest-10_1}
docker-compose/otobo-base.yml:    image: ${OTOBO_IMAGE_OTOBO_ELASTICSEARCH:-rotheross/otobo-elasticsearch:latest-10_1}
docker-compose/otobo-override-https-kerberos.yml:    image: ${OTOBO_IMAGE_OTOBO_NGINX:-rotheross/otobo-nginx-kerberos-webproxy:latest-10_1}
docker-compose/otobo-override-https.yml:    image: ${OTOBO_IMAGE_OTOBO_NGINX:-rotheross/otobo-nginx-webproxy:latest-10_1}
docker-compose/otobo-selenium.yml:    image: ${OTOBO_IMAGE_OTOBO_SELENIUM_CHROME:-rotheross/otobo-selenium-chrome:latest-10_1}
```
This was apparently an oversight. I think that this was not noticed because during development the Docker image is usually also declared in the _.env_ file. The declaration in _.env_ has precedence.

We will fix this in the rel-11_0 branch and try to update the tag.

**Comment by bschmalhofer** [comment] 2024-05-15 09:26
I have updated the _docker-compose/*.yml_ files. 

I've also moved the tag rel-11_0_1 to the commit that includes the fixes. See https://github.com/RotherOSS/otobo-docker/releases/tag/rel-11_0_1 . Moving tags is a bit unusual. In this case it is warranted because the tags in docker-compose are in sync with the releases of OTOBO core. So we can't spontanously create a tag like rel-11_0_2.

**Comment by bschmalhofer** [comment] 2024-05-15 17:21
The moved tag has been successfully used today. 

@nudfmf : as you already have pulled rel-11_0_1 you likely need to call:

```
git fetch --tags --force
git checkout rel-11_0_1
```

**Comment by bschmalhofer** [comment] 2024-06-01 10:16
Closing as this is fixed in rel-11_0_2

**Closed as completed by bschmalhofer** 2024-06-01 10:16 UTC
